name: drinkwithbook
description: "A community app for a bookshop-cafe."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Небольшое уточнение версии Dart
  flutter: '3.35.0' 

dependencies:
  flutter:
    sdk: flutter

  # Базовые пакеты для UI
  cupertino_icons: ^1.0.8

  # Supabase - ядро нашего бэкенда
  supabase_flutter: ^2.1.2

  # Для работы с переменными окружения (.env файл)
  flutter_dotenv: ^5.1.0

  # State Management - управление состоянием приложения (Выбор Riverpod)
  flutter_riverpod: ^2.5.1

  # Для создания неизменяемых моделей и удобной работы с JSON
  freezed_annotation: ^2.4.1

  # Для навигации с улучшенным API
  go_router: ^13.0.0

  # Для красивых и плавных анимаций
  flutter_animate: ^4.3.0

  # Для загрузки и кэширования изображений
  cached_network_image: ^3.3.0

  # Для работы с датами и временем
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Генерация кода для freezed
  build_runner: ^2.4.8
  freezed: ^2.4.5

  # Генерация кода для json_serializable (если решите использовать)
  json_serializable: ^6.7.4

# Секция Flutter
flutter:

  uses-material-design: true

  # Добавьте папку assets для изображений, шрифтов и т.д.
  assets:
    - assets/images/
    - .env # Добавляем файл .env в assets, чтобы он был доступен в приложении

  # Пример добавления кастомных шрифтов (раскомментируйте и настройте по необходимости)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #   - family: Playfair
  #     fonts:
  #       - asset: assets/fonts/PlayfairDisplay-Regular.ttf
  #       - asset: assets/fonts/PlayfairDisplay-Italic.ttf
  #         style: italic